// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeypckhpayuskaztxfbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVleXBja2hwYXl1c2thenR4ZmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzkzODQsImV4cCI6MjA2ODMxNTM4NH0.BlGRjFn006tWshofDh2LAZ5wYQqnSBCHIkuXl0VeUJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});